GDAL 3.9.1 (#136)
* Bump versions

* GDAL tag changed

* CI fixes

* Ensure vcpkg installs package. Debugging cache

* Adjust cache for CI

* Set cache restore keys for CI

* Fix warnings in Dockerfile

* Collect deps for windows

* Fixed DLL packaging inconsistency

diff --git a/osx/vcpkg-makefile b/osx/vcpkg-makefile
--- a/osx/vcpkg-makefile
+++ b/osx/vcpkg-makefile
@@ -107,8 +107,24 @@ patch_vcpkg_triplets:
 	@echo "$$VCPKG_TRIPLET_OSX_STATIC_RELEASE" > $(VCPKG_ROOT)/custom-triplets/$(VCPKG_RID).cmake
 
 install_packages:
-	@$(foreach pack,$(VCPKG_REQUIRE_OSX),MAKELEVEL=0 $(VCPKG) install $(pack):$(VCPKG_RID) $(VCPKG_PARAMS_INSTALL);)
-	@$(foreach pack,$(VCPKG_REQUIRE_OSX_DYNAMIC), MAKELEVEL=0 $(VCPKG) install $(pack):$(VCPKG_RID)-dynamic $(VCPKG_PARAMS_INSTALL);)
+	@for pack in $(VCPKG_REQUIRE_OSX); do \
+		{ (MAKELEVEL=0 $(VCPKG) install $$pack:$(VCPKG_RID) $(VCPKG_PARAMS_INSTALL) $(VCPKG_ENSURE_INSTALLED)) || \
+		(if [ $$? -ne 0 ]; then \
+			echo "Error occurred while installing $$pack"; \
+			cat $(VCPKG_ROOT)/buildtrees/$$pack/*err.log; \
+			cat $(VCPKG_ROOT)/buildtrees/$$pack/*out.log; \
+		fi; exit 1) \
+	}; \
+	done
+	@for pack in $(VCPKG_REQUIRE_OSX_DYNAMIC); do \
+		{ (MAKELEVEL=0 $(VCPKG) install $$pack:$(VCPKG_RID)-dynamic $(VCPKG_PARAMS_INSTALL) $(VCPKG_ENSURE_INSTALLED)) || \
+		(if [ $$? -ne 0 ]; then \
+			echo "Error occurred while installing $$pack"; \
+			cat $(VCPKG_ROOT)/buildtrees/$$pack/*err.log; \
+			cat $(VCPKG_ROOT)/buildtrees/$$pack/*out.log; \
+		fi; exit 1) \
+	}; \
+	done
 
 remove_packages:
 	@$(foreach pack,$(VCPKG_REQUIRE_OSX), $(VCPKG) remove $(pack):$(VCPKG_RID) $(VCPKG_PARAMS_REMOVE);)
